/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import drugstore.medicine_list;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;

/**
 *
 * @author bustamantecr_sd2022
 */
public class Dashboard_UI extends JFrame {

    /**
     * Creates new form Dashboard_UI
     */
    public Dashboard_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coughLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        cough1Label = new javax.swing.JLabel();
        genNameLabel10 = new javax.swing.JLabel();
        bNameLabel10 = new javax.swing.JLabel();
        priceLabel10 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        cbLabel = new javax.swing.JLabel();
        cgenLabel = new javax.swing.JLabel();
        purchase1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        aq1Label = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        cough2 = new javax.swing.JLabel();
        genNameLabel9 = new javax.swing.JLabel();
        bNameLabel9 = new javax.swing.JLabel();
        priceLabel9 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        cgen2Label = new javax.swing.JLabel();
        cb2Label = new javax.swing.JLabel();
        purchase2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        aq1Label1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cough3 = new javax.swing.JLabel();
        genNameLabel11 = new javax.swing.JLabel();
        bNameLabel11 = new javax.swing.JLabel();
        priceLabel11 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        cb3Label = new javax.swing.JLabel();
        cgen3Label = new javax.swing.JLabel();
        purchase3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        aq1Label2 = new javax.swing.JLabel();
        headacheLabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        headache1 = new javax.swing.JLabel();
        genNameLabel6 = new javax.swing.JLabel();
        bNameLabel6 = new javax.swing.JLabel();
        priceLabel6 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        hgen1Label = new javax.swing.JLabel();
        hb1Label = new javax.swing.JLabel();
        purchase4 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        genNameLabel7 = new javax.swing.JLabel();
        bNameLabel7 = new javax.swing.JLabel();
        priceLabel7 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        hg2Label = new javax.swing.JLabel();
        hb2Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        purchase5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        headache3 = new javax.swing.JLabel();
        genNameLabel8 = new javax.swing.JLabel();
        bNameLabel8 = new javax.swing.JLabel();
        priceLabel8 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        hg3Label = new javax.swing.JLabel();
        hb3Label = new javax.swing.JLabel();
        purchase6 = new javax.swing.JButton();
        allergyLabel = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        allergy1 = new javax.swing.JLabel();
        genNameLabel3 = new javax.swing.JLabel();
        priceLabel3 = new javax.swing.JLabel();
        bNameLabel3 = new javax.swing.JLabel();
        ag1Label = new javax.swing.JLabel();
        ab1Label = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        purchase7 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        allergy2 = new javax.swing.JLabel();
        genNameLabel4 = new javax.swing.JLabel();
        bNameLabel4 = new javax.swing.JLabel();
        priceLabel4 = new javax.swing.JLabel();
        ag2Label = new javax.swing.JLabel();
        ab2Label = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        purchase8 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        allergy3 = new javax.swing.JLabel();
        genNameLabel5 = new javax.swing.JLabel();
        bNameLabel5 = new javax.swing.JLabel();
        priceLabel5 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        ab3Label = new javax.swing.JLabel();
        ag3Label = new javax.swing.JLabel();
        purchase9 = new javax.swing.JButton();
        painLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bp1 = new javax.swing.JLabel();
        genNameLabel2 = new javax.swing.JLabel();
        bNameLabel2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        bpg1Label = new javax.swing.JLabel();
        bpb1Label = new javax.swing.JLabel();
        price10 = new javax.swing.JLabel();
        purchase10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bp2 = new javax.swing.JLabel();
        genNameLabel1 = new javax.swing.JLabel();
        bNameLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        bpg2Label = new javax.swing.JLabel();
        bpb2Label = new javax.swing.JLabel();
        price11 = new javax.swing.JLabel();
        purchase11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bp3 = new javax.swing.JLabel();
        genNameLabel = new javax.swing.JLabel();
        bpg3Label = new javax.swing.JLabel();
        bNameLabel = new javax.swing.JLabel();
        bpb3Label = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        price12 = new javax.swing.JLabel();
        purchase12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel18.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel1.setText("TambalKO");

        logoutButton.setText("Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 749, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        welcomeLabel.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        welcomeLabel.setText("Welcome to TambalKo");

        jLabel2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel2.setText("\"We always Make Time for You!\"");

        coughLabel.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        coughLabel.setText("Medicine For Cough");

        cough1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/cough2.jpg"))); // NOI18N

        genNameLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel10.setText("Generic Name : ");

        bNameLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel10.setText("Brand Name :");

        priceLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel10.setText("Price : ");

        price1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price1.setText("8.00");

        cbLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cbLabel.setText("Mucinex");

        cgenLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cgenLabel.setText("Guaifenesin");

        purchase1.setText("Purchase");
        purchase1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        aq1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(cough1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel10)
                            .addComponent(bNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genNameLabel10))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cgenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(aq1Label)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(purchase1)
                .addGap(27, 27, 27))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(cough1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cgenLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel10)
                    .addComponent(cbLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel10)
                    .addComponent(price1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aq1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(purchase1)
                .addContainerGap())
        );

        cough2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/cough1.jpg"))); // NOI18N

        genNameLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel9.setText("Generic Name : ");

        bNameLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel9.setText("Brand Name :");

        priceLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel9.setText("Price : ");

        price2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price2.setText("8.00");

        cgen2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cgen2Label.setText("Acetaminophen");

        cb2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cb2Label.setText("Theraflu");

        purchase2.setText("Purchase");
        purchase2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        aq1Label1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(cough2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(genNameLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cgen2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aq1Label1)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(purchase2)
                .addGap(19, 19, 19))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cough2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cgen2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel9)
                    .addComponent(cb2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel9)
                    .addComponent(price2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(aq1Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(purchase2)
                .addContainerGap())
        );

        cough3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/cough3.jpg"))); // NOI18N
        cough3.setText("jLabel3");

        genNameLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel11.setText("Generic Name : ");

        bNameLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel11.setText("Brand Name :");

        priceLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel11.setText("Price : ");

        price3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price3.setText("8.00");

        cb3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cb3Label.setText("Cheratussin AC");

        cgen3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cgen3Label.setText("Codeine");

        purchase3.setText("Purchase");
        purchase3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        aq1Label2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(cough3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(genNameLabel11))
                                            .addComponent(priceLabel11))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cgen3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(aq1Label2)))))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(purchase3)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cough3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cgen3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel11)
                    .addComponent(cb3Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel11)
                    .addComponent(price3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(aq1Label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(purchase3)
                .addContainerGap())
        );

        headacheLabel.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        headacheLabel.setText("Medicine For Headache");

        headache1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/headache1.jpg"))); // NOI18N

        genNameLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel6.setText("Generic Name : ");

        bNameLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel6.setText("Brand Name :");

        priceLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel6.setText("Price : ");

        price4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price4.setText("8.00");

        hgen1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hgen1Label.setText("Acetaminophen");

        hb1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hb1Label.setText("Tylenol");

        purchase4.setText("Purchase");
        purchase4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(headache1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hb1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(priceLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(purchase4))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(genNameLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(hgen1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headache1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hgen1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel6)
                    .addComponent(hb1Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel6)
                    .addComponent(price4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(purchase4)
                .addGap(29, 29, 29))
        );

        genNameLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel7.setText("Generic Name : ");

        bNameLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel7.setText("Brand Name :");

        priceLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel7.setText("Price : ");

        price5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price5.setText("8.00");

        hg2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hg2Label.setText("Ibuprofen");

        hb2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hb2Label.setText("Advil");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/headache2.jpg"))); // NOI18N

        purchase5.setText("Purchase");
        purchase5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genNameLabel7)
                            .addComponent(bNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel7))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hb2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hg2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase5)
                .addGap(28, 28, 28))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hg2Label))
                .addGap(13, 13, 13)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel7)
                    .addComponent(hb2Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel7)
                    .addComponent(price5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase5)
                .addGap(21, 21, 21))
        );

        headache3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/headache3.jpg"))); // NOI18N

        genNameLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel8.setText("Generic Name : ");

        bNameLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel8.setText("Brand Name :");

        priceLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel8.setText("Price : ");

        price6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price6.setText("8.00");

        hg3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hg3Label.setText("Codeine");

        hb3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        hb3Label.setText("Fioricet");

        purchase6.setText("Purchase");
        purchase6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(priceLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(purchase6)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(headache3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(genNameLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hg3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(bNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(hb3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headache3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hg3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel8)
                    .addComponent(hb3Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel8)
                    .addComponent(price6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(purchase6)
                .addGap(26, 26, 26))
        );

        allergyLabel.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        allergyLabel.setText("Medicine For Allergy");

        allergy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/allergy1.jpg"))); // NOI18N

        genNameLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel3.setText("Generic Name : ");

        priceLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel3.setText("Price : ");

        bNameLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel3.setText("Brand Name :");

        ag1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ag1Label.setText("Diphenhydramine");

        ab1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ab1Label.setText("Benadryl");

        price7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price7.setText("8.00");

        purchase7.setText("Purchase");
        purchase7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genNameLabel3)
                            .addComponent(bNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ab1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ag1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(purchase7)
                .addGap(25, 25, 25))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ag1Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel3)
                    .addComponent(ab1Label))
                .addGap(23, 23, 23)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel3)
                    .addComponent(price7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(purchase7)
                .addGap(26, 26, 26))
        );

        allergy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/allergy2.jpg"))); // NOI18N

        genNameLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel4.setText("Generic Name : ");

        bNameLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel4.setText("Brand Name :");

        priceLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel4.setText("Price : ");

        ag2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ag2Label.setText("Loratadine");

        ab2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ab2Label.setText("Claritin");

        price8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price8.setText("8.00");

        purchase8.setText("Purchase");
        purchase8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(genNameLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ag2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(bNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ab2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(priceLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(purchase8)
                .addGap(33, 33, 33))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ag2Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel4)
                    .addComponent(ab2Label))
                .addGap(29, 29, 29)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel4)
                    .addComponent(price8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase8)
                .addGap(24, 24, 24))
        );

        allergy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/allergy3.jpg"))); // NOI18N

        genNameLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel5.setText("Generic Name : ");

        bNameLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel5.setText("Brand Name :");

        priceLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel5.setText("Price : ");

        price9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price9.setText("8.00");

        ab3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ab3Label.setText("Xyzal");

        ag3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ag3Label.setText(" Levocetirizine");

        purchase9.setText("Purchase");
        purchase9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(genNameLabel5)
                                .addGap(36, 36, 36)
                                .addComponent(ag3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(priceLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ab3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase9)
                .addGap(28, 28, 28))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ag3Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel5)
                    .addComponent(ab3Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel5)
                    .addComponent(price9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase9)
                .addGap(25, 25, 25))
        );

        painLabel.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        painLabel.setText("Medicine For Body Pain");

        bp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/body1.jpg"))); // NOI18N

        genNameLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel2.setText("Generic Name : ");

        bNameLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel2.setText("Brand Name :");

        priceLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel2.setText("Price : ");

        bpg1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bpg1Label.setText("Aspirin");

        bpb1Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bpb1Label.setText("Bayer");

        price10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price10.setText("8.00");

        purchase10.setText("Purchase");
        purchase10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bp1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genNameLabel2)
                            .addComponent(bNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpb1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpg1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase10)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bp1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpg1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel2)
                    .addComponent(bpb1Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel2)
                    .addComponent(price10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase10)
                .addGap(22, 22, 22))
        );

        bp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/body2.jpg"))); // NOI18N

        genNameLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel1.setText("Generic Name : ");

        bNameLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel1.setText("Brand Name :");

        priceLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel1.setText("Price : ");

        bpg2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bpg2Label.setText("Naproxyn");

        bpb2Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bpb2Label.setText("Aleve");

        price11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price11.setText("8.00");

        purchase11.setText("Purchase");
        purchase11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(bp2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genNameLabel1)
                            .addComponent(bNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price11)
                            .addComponent(bpb2Label)
                            .addComponent(bpg2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(purchase11)
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bp2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpg2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel1)
                    .addComponent(bpb2Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel1)
                    .addComponent(price11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(purchase11)
                .addGap(22, 22, 22))
        );

        bp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/body3.jpg"))); // NOI18N

        genNameLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        genNameLabel.setText("Generic Name : ");

        bpg3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bpg3Label.setText("Ibuprofen");

        bNameLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bNameLabel.setText("Brand Name :");

        bpb3Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bpb3Label.setText("Motrin");

        priceLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        priceLabel.setText("Price : ");

        price12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        price12.setText("8.00");

        purchase12.setText("Purchase");
        purchase12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(purchase12)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(bp3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(priceLabel))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(genNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bpb3Label)
                    .addComponent(bpg3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price12))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bp3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpg3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpb3Label)
                    .addComponent(bNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(price12))
                .addGap(37, 37, 37)
                .addComponent(purchase12)
                .addGap(23, 23, 23))
        );

        jButton2.setText("Done");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(coughLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(683, 683, 683)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(headacheLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allergyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(painLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel2)))
                .addContainerGap(1071, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(coughLabel))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(headacheLabel)
                .addGap(37, 37, 37)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(allergyLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(painLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1569, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Purchase_UI purchase = new Purchase_UI();
//    DrugStore_UI login = new DrugStore_UI();
    static ArrayList<medicine_list> Purchase = new ArrayList<>();
    
    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        new DrugStore_UI();
        this.dispose();

    }//GEN-LAST:event_logoutButtonMouseClicked

    private void purchase1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase1MouseClicked
        String generic = this.cgenLabel.getText();
        String brand = this.cbLabel.getText();
        String price1 = this.price1.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
//        for(int i=0; i< Purchase.size(); i++){
//            System.out.println(Purchase.get(i).getBrandName());
//        }
//        System.out.println(Arrays.toString(Purchase));

    }//GEN-LAST:event_purchase1MouseClicked

    private void purchase2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase2MouseClicked
        String generic = this.cgen2Label.getText();
        String brand = this.cb2Label.getText();
        String price1 = this.price2.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase2MouseClicked

    private void purchase3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase3MouseClicked
        String generic = this.cgen3Label.getText();
        String brand = this.cb3Label.getText();
        String price1 = this.price3.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase3MouseClicked

    private void purchase4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase4MouseClicked
        String generic = this.hgen1Label.getText();
        String brand = this.hb1Label.getText();
        String price1 = this.price4.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase4MouseClicked

    private void purchase5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase5MouseClicked
       String generic = this.hg2Label.getText();
        String brand = this.hb2Label.getText();
        String price1 = this.price5.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase5MouseClicked

    private void purchase6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase6MouseClicked
        String generic = this.hg3Label.getText();
        String brand = this.hb3Label.getText();
        String price1 = this.price6.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase6MouseClicked

    private void purchase7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase7MouseClicked
        String generic = this.ag1Label.getText();
        String brand = this.ab1Label.getText();
        String price1 = this.price7.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase7MouseClicked

    private void purchase8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase8MouseClicked
        String generic = this.ag2Label.getText();
        String brand = this.ab2Label.getText();
        String price1 = this.price8.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase8MouseClicked

    private void purchase9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase9MouseClicked
        String generic = this.ag3Label.getText();
        String brand = this.ag3Label.getText();
        String price1 = this.price9.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase9MouseClicked

    private void purchase10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase10MouseClicked
        String generic = this.bpg1Label.getText();
        String brand = this.bpb1Label.getText();
        String price1 = this.price10.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase10MouseClicked

    private void purchase11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase11MouseClicked
        String generic = this.bpg2Label.getText();
        String brand = this.bpb2Label.getText();
        String price1 = this.price11.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase11MouseClicked

    private void purchase12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase12MouseClicked
        String generic = this.bpg3Label.getText();
        String brand = this.bpb3Label.getText();
        String price1 = this.price12.getText();
        Double price = Double.parseDouble(price1);

        medicine_list m = new medicine_list(generic, brand, price, 0);
        Purchase.add(m);
    }//GEN-LAST:event_purchase12MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
        Purchase_UI purchase_UI = new Purchase_UI();
        purchase_UI.setVisible(true);
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ab1Label;
    private javax.swing.JLabel ab2Label;
    private javax.swing.JLabel ab3Label;
    private javax.swing.JLabel ag1Label;
    private javax.swing.JLabel ag2Label;
    private javax.swing.JLabel ag3Label;
    private javax.swing.JLabel allergy1;
    private javax.swing.JLabel allergy2;
    private javax.swing.JLabel allergy3;
    private javax.swing.JLabel allergyLabel;
    private javax.swing.JLabel aq1Label;
    private javax.swing.JLabel aq1Label1;
    private javax.swing.JLabel aq1Label2;
    private javax.swing.JLabel bNameLabel;
    private javax.swing.JLabel bNameLabel1;
    private javax.swing.JLabel bNameLabel10;
    private javax.swing.JLabel bNameLabel11;
    private javax.swing.JLabel bNameLabel2;
    private javax.swing.JLabel bNameLabel3;
    private javax.swing.JLabel bNameLabel4;
    private javax.swing.JLabel bNameLabel5;
    private javax.swing.JLabel bNameLabel6;
    private javax.swing.JLabel bNameLabel7;
    private javax.swing.JLabel bNameLabel8;
    private javax.swing.JLabel bNameLabel9;
    private javax.swing.JLabel bp1;
    private javax.swing.JLabel bp2;
    private javax.swing.JLabel bp3;
    private javax.swing.JLabel bpb1Label;
    private javax.swing.JLabel bpb2Label;
    private javax.swing.JLabel bpb3Label;
    private javax.swing.JLabel bpg1Label;
    private javax.swing.JLabel bpg2Label;
    private javax.swing.JLabel bpg3Label;
    private javax.swing.JLabel cb2Label;
    private javax.swing.JLabel cb3Label;
    private javax.swing.JLabel cbLabel;
    private javax.swing.JLabel cgen2Label;
    private javax.swing.JLabel cgen3Label;
    private javax.swing.JLabel cgenLabel;
    private javax.swing.JLabel cough1Label;
    private javax.swing.JLabel cough2;
    private javax.swing.JLabel cough3;
    private javax.swing.JLabel coughLabel;
    private javax.swing.JLabel genNameLabel;
    private javax.swing.JLabel genNameLabel1;
    private javax.swing.JLabel genNameLabel10;
    private javax.swing.JLabel genNameLabel11;
    private javax.swing.JLabel genNameLabel2;
    private javax.swing.JLabel genNameLabel3;
    private javax.swing.JLabel genNameLabel4;
    private javax.swing.JLabel genNameLabel5;
    private javax.swing.JLabel genNameLabel6;
    private javax.swing.JLabel genNameLabel7;
    private javax.swing.JLabel genNameLabel8;
    private javax.swing.JLabel genNameLabel9;
    private javax.swing.JLabel hb1Label;
    private javax.swing.JLabel hb2Label;
    private javax.swing.JLabel hb3Label;
    private javax.swing.JLabel headache1;
    private javax.swing.JLabel headache3;
    private javax.swing.JLabel headacheLabel;
    private javax.swing.JLabel hg2Label;
    private javax.swing.JLabel hg3Label;
    private javax.swing.JLabel hgen1Label;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel painLabel;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price10;
    private javax.swing.JLabel price11;
    private javax.swing.JLabel price12;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel10;
    private javax.swing.JLabel priceLabel11;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JLabel priceLabel5;
    private javax.swing.JLabel priceLabel6;
    private javax.swing.JLabel priceLabel7;
    private javax.swing.JLabel priceLabel8;
    private javax.swing.JLabel priceLabel9;
    private javax.swing.JButton purchase1;
    private javax.swing.JButton purchase10;
    private javax.swing.JButton purchase11;
    private javax.swing.JButton purchase12;
    private javax.swing.JButton purchase2;
    private javax.swing.JButton purchase3;
    private javax.swing.JButton purchase4;
    private javax.swing.JButton purchase5;
    private javax.swing.JButton purchase6;
    private javax.swing.JButton purchase7;
    private javax.swing.JButton purchase8;
    private javax.swing.JButton purchase9;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
